stages:
- clean
- deploy

reybot-clean:
  stage: clean
  allow_failure: true
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker stop ReyBot
    - docker rm ReyBot


reybot-deploy:
  stage: deploy
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker build . -f bot.Dockerfile -t Rey/rey_bot:latest
    - docker tag Rey/rey_bot localhost:5000/rey_bot
    - docker push localhost:5000/rey_bot
    - docker run -d --name ReyBot localhost:5000/rey_bot:latest