stages:
- clean
- build
- deploy

reybot-clean:
  stage: clean
  allow_failure: true
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker stop reybot
    - docker rm reybot


reybot-test:
  stage: build
  allow_failure: true
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker build . -f bot.Dockerfile -t rey/rey_bot:latest
    - docker tag rey/rey_bot localhost:5000/rey_bot
    - docker push localhost:5000/rey_bot
    - docker run --name reybot -p 58913:58913 localhost:5000/rey_bot:latest

reybot-deploy:
  stage: deploy
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker-compose up -d