stages:
- clean
- build
- deploy
- run

reybot-clean:
  stage: clean
  allow_failure: true
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker stop reybot
    - docker rm reybot

reybot-build:
  stage: build
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker build . -f bot.Dockerfile -t rey/rey_bot:latest

reybot-deploy:
  stage: deploy
  tags:
    - rey-discord-bot
  only:
    - master
  script:
    - docker compose up -d

reybot-logs-live:
    stage: run
    when: manual
    tags:
        - rey-discord-bot
    script:
        - docker logs -f reybot --tail 1000

reybot-restart:
    stage: run
    when: manual
    tags:
        - rey-discord-bot
    script:
        - docker restart reybot