version: '3'
services:
  reybot:
    image: localhost:5000/rey_bot:latest
    container_name: reybot
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MAIN_ADMIN: ${MAIN_ADMIN}
      ADMIN_IDS: ${ADMIN_IDS}
      REYBOT_DEBUG: ${REYBOT_DEBUG}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GI_LTUID: ${GI_LTUID}
      GI_LTOKEN: ${GI_LTOKEN}
      GI_UUID: ${GI_UUID}
      MAIN_GUILD: ${MAIN_GUILD}
      SERVICE_ID: ${SERVICE_ID}